name: 'platformOS/CaptureBaseSnaphosts'
description: capture-base-snapshots
inputs:
  base:
    required: true
    description: base branch for PR
  test-name:
    description: 'test name'
    required: true
  before:
    required: false
  after:
    required: false
  skip:
    required: false
  npm-prefix:
    required: false
    default: "."
runs:
  using: "composite"
  steps:

      - name: before ${{ inputs.test-name }}
        if: ${{ inputs.before && !inputs.skip }}
        shell: sh
        run: |
          ${{ inputs.before }}

      - name: run ${{ inputs.test-name }}
        env:
          REPORT_TYPE: ${{ inputs.test-name }}
        if: ${{ !inputs.skip }}
        shell: sh
        run: |
          set -e
          npm run ${{ inputs.test-name }} --prefix ${{ inputs.npm-prefix }}

      - name: create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          base: ${{ inputs.base }}
          branch-suffix: timestamp

      - name: after ${{ inputs.test-name }}
        if: ${{ inputs.after && !inputs.skip }}
        shell: sh
        run: |
          ${{ inputs.after }}

      - name: summary
        if: ${{ !inputs.skip && always() }}
        shell: sh
        run: |
          REPORT_TYPE=${{ inputs.test-name }}
          echo "### FAILED $REPORT_TYPE tests report -> $UPLOAD_HOST/$REPORT_PATH-$REPORT_TYPE" >> $GITHUB_STEP_SUMMARY

      - name: skip ${{ inputs.test-name }}
        if: ${{ !!inputs.skip }}
        shell: sh
        run: echo skipping ${{ inputs.test-name }}
