name: 'platformOS/CaptureBaseSnaphosts'
description: capture-base-snapshots
inputs:
  base:
    required: true
    description: base branch for PR
  npm-prefix:
    required: false
    description: directory where package.json for tests is located
    default: .
    type: string
  resolution:
    description: screen resolution
    required: true
  test-name:
    description: test name
    required: true
  before:
    required: false
  after:
    required: false
  skip:
    required: false
runs:
  using: "composite"
  steps:

      - name: before ${{ inputs.test-name }}
        if: ${{ inputs.before && !inputs.skip }}
        shell: sh
        run: |
          ${{ inputs.before }}

      - name: run ${{ inputs.test-name }}
        env:
          REPORT_TYPE: ${{ inputs.test-name }}
        if: ${{ !inputs.skip }}
        run: |
          npm run ${{ inputs.test-name }} --prefix ${{ inputs.npm-prefix }}

      - name: archive screenshots
        if: ${{ !inputs.skip }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.resolution }}
          path: ./tests/visual-tests/snapshots/${{ inputs.resolution }}

      - name: after ${{ inputs.test-name }}
        if: ${{ inputs.after && !inputs.skip }}
        shell: sh
        run: |
          ${{ inputs.after }}

      - name: summary
        if: ${{ !inputs.skip && always() }}
        shell: sh
        run: |
          REPORT_TYPE=${{ inputs.test-name }}
          echo "### $REPORT_TYPE tests report" >> $GITHUB_STEP_SUMMARY
          echo "#### Status: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY

      - name: skip ${{ inputs.test-name }}
        if: ${{ !!inputs.skip }}
        shell: sh
        run: echo skipping ${{ inputs.test-name }}
